paths:
  # CSV-style input
  real_dist_file:  "data/real_world_dis_info_rgb.xlsx"
  input_dir: "data/raw_synthetic/training_data/data_5k"

  # Multi-category full plots
  m_plots_svg:  "data/synthetic_plots/multi_cat/training/svgs"
  m_plots: "data/synthetic_plots/multi_cat/training/images"
  m_axes_file: "data/synthetic_plots/multi_cat/training/axes_annotations.json"
  m_dist_file: "data/synthetic_plots/multi_cat/training/dist_annotations.json"

  # Multi-category crops
  m_crops: "data/synthetic_plots/multi_cat/training/crops/images"
  m_all_json: "data/synthetic_plots/multi_cat/training/crops/all_data.json"
  m_train_json: "data/synthetic_plots/multi_cat/training/crops/train.json"
  m_valid_json: "data/synthetic_plots/multi_cat/training/crops/valid.json"

  # Mult-Category Ground truth plots
  m_gt_plots: "data/synthetic_plots/multi_cat/training/gt/images"
  m_gt_axes_file: "data/synthetic_plots/multi_cat/training/gt/gt_axes_annotations.json"
  m_gt_crops: "data/synthetic_plots/multi_cat/training/gt/gt_crops"
  m_gt_line_color: "data/synthetic_plots/multi_cat/training/gt/gt_line_color.json"
  
  # Ground truth plots for individual category
  m_gt_plots_cat: "data/synthetic_plots/multi_cat/training/gt/gt_cat"
  m_gt_plots_cat_crops: "data/synthetic_plots/multi_cat/training/gt/gt_cat_crops"
  m_gt_plots_cat_ntl: "data/synthetic_plots/multi_cat/training/gt/gt_cat_ntl"
  m_gt_plots_cat_ntl_crops: "data/synthetic_plots/multi_cat/training/gt/gt_cat_ntl_crops"



  # Category separation - color
  m_color_sep_plots: "data/synthetic_plots/multi_cat/training/color/images"
  m_color_all_json: "data/synthetic_plots/multi_cat/training/color/images/all_data.json"
  m_color_rescaled_all_json: "data/synthetic_plots/multi_cat/training/color/images/rescaled_all_data.json"
  m_color_train_json: "data/synthetic_plots/multi_cat/training/color/train.json"
  m_color_valid_json: "data/synthetic_plots/multi_cat/training/color/valid.json"


  # Category separation - color with white background
  m_color_sep_plots_wbg: "data/synthetic_plots/multi_cat/training/color_wbg/images"
  m_color_wbg_all_json: "data/synthetic_plots/multi_cat/training/color_wbg/images/all_data.json"
  m_color_wbg_train_json: "data/synthetic_plots/multi_cat/training/color_wbg/train.json"
  m_color_wbg_valid_json: "data/synthetic_plots/multi_cat/training/color_wbg/valid.json"
  m_color_line_color: "data/synthetic_plots/multi_cat/training/color/line_color.json"
  m_color_denoised_plots: "data/synthetic_plots/multi_cat/training/color_denoised"

  # Category separation - clustering
  m_cluster_sep_plots: "data/synthetic_plots/multi_cat/training/cluster/images"
  m_cluster_all_json: "data/synthetic_plots/multi_cat/training/cluster/images/all_data.json"
  m_cluster_rescaled_all_json: "data/synthetic_plots/multi_cat/training/cluster/rescaled_all_data.json"
  m_cluster_train_json: "data/synthetic_plots/multi_cat/training/cluster/train.json"
  m_cluster_valid_json: "data/synthetic_plots/multi_cat/training/cluster/valid.json"


  # Single-category
  s_plots: "data/synthetic_plots/single_cat/training/images"
  s_axes_file: "data/synthetic_plots/single_cat/training/axes_annotations.json"
  s_dist_file: "data/synthetic_plots/single_cat/training/dist_annotations.json"
  s_crops: "data/synthetic_plots/single_cat/training/s_crops/images"
  s_all_json: "data/synthetic_plots/single_cat/training/s_crops/all_data.json"

unet:
  chkpt_path: "outputs/chkpt/0810-25_1529-52/unet_sd_cluster_mse_model_epoch80.pth"
  #input_dir: "data/real_plots/cluster/images"  same as color separated paths
  output_dir: "data/synthetic_plots/multi_cat/training/color/denoised"
  output_dir_cluster: "data/synthetic_plots/multi_cat/training/cluster/denoised"




