paths:
  # CSV-style input
  real_dist_file:  "data/real_world_dis_info_rgb.xlsx"
  input_dir: "data/raw_synthetic/training_data/data_5k"

  # Multi-category full plots
  m_plots_svg:  "data/synthetic_plots/multi_cat/training/svgs"
  m_plots: "data/synthetic_plots/multi_cat/training/images"
  m_axes_file: "data/synthetic_plots/multi_cat/training/axes_annotations.json"
  m_dist_file: "data/synthetic_plots/multi_cat/training/dist_annotations.json"

  # Multi-category crops
  m_crops: "data/synthetic_plots/multi_cat/training/crops/images"
  m_all_json: "data/synthetic_plots/multi_cat/training/crops/all_data.json"
  m_train_json: "data/synthetic_plots/multi_cat/training/crops/train.json"
  m_valid_json: "data/synthetic_plots/multi_cat/training/crops/valid.json"

  # Mult-Category Ground truth plots
  m_gt_plots: "data/synthetic_plots/multi_cat/training/gt/images"
  m_gt_axes_file: "data/synthetic_plots/multi_cat/training/gt/gt_axes_annotations.json"
  m_gt_crops: "data/synthetic_plots/multi_cat/training/gt/gt_crops"
  m_gt_line_color: "data/synthetic_plots/multi_cat/training/gt/gt_line_color.json"
  
  # Ground truth plots for individual category
  m_gt_plots_cat: "data/synthetic_plots/multi_cat/training/gt/gt_cat"
  m_gt_plots_cat_crops: "data/synthetic_plots/multi_cat/training/gt/gt_cat_crops"
  m_gt_plots_cat_ntl: "data/synthetic_plots/multi_cat/training/gt/gt_cat_ntl"
  m_gt_plots_cat_ntl_crops: "data/synthetic_plots/multi_cat/training/gt/gt_cat_ntl_crops"



  # Category separation - color
  m_color_sep_plots: "data/synthetic_plots/multi_cat/training/color/images"
  m_color_all_json: "data/synthetic_plots/multi_cat/training/color/images/all_data.json"
  m_color_rescaled_all_json: "data/synthetic_plots/multi_cat/training/color/images/rescaled_all_data.json"
  m_color_train_json: "data/synthetic_plots/multi_cat/training/color/train.json"
  m_color_valid_json: "data/synthetic_plots/multi_cat/training/color/valid.json"

  # category separation - using hue filtering and dbscan filtering
  m_hdbscan_sep_plots: "data/synthetic_plots/multi_cat/training/hdbscan/images"
  m_hdbscan_all_json: "data/synthetic_plots/multi_cat/training/hdbscan/images/all_data.json"
  m_hdbscan_rescaled_all_json: "data/synthetic_plots/multi_cat/training/hdbscan/rescaled_all_data.json"
  m_hdbscan_train_json: "data/synthetic_plots/multi_cat/training/hdbscan/train.json"
  m_hdbscan_valid_json: "data/synthetic_plots/multi_cat/training/hdbscan/valid.json"



  # Category separation - color with white background
  m_color_sep_plots_wbg: "data/synthetic_plots/multi_cat/training/color_wbg/images"
  m_color_wbg_all_json: "data/synthetic_plots/multi_cat/training/color_wbg/images/all_data.json"
  m_color_wbg_train_json: "data/synthetic_plots/multi_cat/training/color_wbg/train.json"
  m_color_wbg_valid_json: "data/synthetic_plots/multi_cat/training/color_wbg/valid.json"
  m_color_line_color: "data/synthetic_plots/multi_cat/training/color/line_color.json"
  m_color_denoised_plots: "data/synthetic_plots/multi_cat/training/color_denoised"

  # Category separation - clustering dbscan downnsampled
  m_cluster_sep_plots: "data/synthetic_plots/multi_cat/training/cluster/images"
  m_cluster_all_json: "data/synthetic_plots/multi_cat/training/cluster/images/all_data.json"
  m_cluster_rescaled_all_json: "data/synthetic_plots/multi_cat/training/cluster/rescaled_all_data.json"
  m_cluster_train_json: "data/synthetic_plots/multi_cat/training/cluster/train.json"
  m_cluster_valid_json: "data/synthetic_plots/multi_cat/training/cluster/valid.json"


  # category separation - using hue filtering and dbscan filtering
  m_peak_sep_plots: "data/synthetic_plots/multi_cat/training/peak/images"
  m_peak_all_json: "data/synthetic_plots/multi_cat/training/peak/images/all_data.json"
  m_peak_rescaled_all_json: "data/synthetic_plots/multi_cat/training/peak/rescaled_all_data.json"
  m_peak_train_json: "data/synthetic_plots/multi_cat/training/peak/train.json"
  m_peak_valid_json: "data/synthetic_plots/multi_cat/training/peak/valid.json"

  # Category separation - clustering elbo downsampled
  m_elbo_sep_plots: "data/synthetic_plots/multi_cat/training/elbo/images"
  m_elbo_all_json: "data/synthetic_plots/multi_cat/training/elbo/images/all_data.json"
  m_elbo_rescaled_all_json: "data/synthetic_plots/multi_cat/training/elbo/rescaled_all_data.json"
  m_elbo_train_json: "data/synthetic_plots/multi_cat/training/elbo/train.json"
  m_elbo_valid_json: "data/synthetic_plots/multi_cat/training/elbo/valid.json"


  # Category separation - clustering elbo full resolution
  m_elbofres_sep_plots: "data/synthetic_plots/multi_cat/training/elbofres/images"
  m_elbofres_all_json: "data/synthetic_plots/multi_cat/training/elbofres/images/all_data.json"
  m_elbofres_rescaled_all_json: "data/synthetic_plots/multi_cat/training/elbofres/rescaled_all_data.json"
  m_elbofres_train_json: "data/synthetic_plots/multi_cat/training/elbofres/train.json"
  m_elbofres_valid_json: "data/synthetic_plots/multi_cat/training/elbofres/valid.json"

  # clustering using LAB color space
  m_lab_cluster_sep_plots: "data/synthetic_plots/multi_cat/training/lab_cluster/images"
  m_lab_cluster_all_json: "data/synthetic_plots/multi_cat/training/lab_cluster/images/all_data.json"
  m_lab_cluster_rescaled_all_json: "data/synthetic_plots/multi_cat/training/lab_cluster/rescaled_all_data.json"
  m_lab_cluster_train_json: "data/synthetic_plots/multi_cat/training/lab_cluster/train.json"
  m_lab_cluster_valid_json: "data/synthetic_plots/multi_cat/training/lab_cluster/valid.json"

  m_lab_cluster_denoised_plots: "data/synthetic_plots/multi_cat/training/lab_cluster/denoised"



  # Single-category
  s_plots: "data/synthetic_plots/single_cat/training/images"
  s_axes_file: "data/synthetic_plots/single_cat/training/axes_annotations.json"
  s_dist_file: "data/synthetic_plots/single_cat/training/dist_annotations.json"
  s_crops: "data/synthetic_plots/single_cat/training/s_crops/images"
  s_all_json: "data/synthetic_plots/single_cat/training/s_crops/all_data.json"


  # evaluation scripts color
  m_color_cat_eval_json: "data/synthetic_plots/multi_cat/training/color/cat_eval_summary.json"
  m_color_cat_eval_crop_csv: "data/synthetic_plots/multi_cat/training/color/per_crop_results.csv"
  m_color_cat_eval_base_csv: "data/synthetic_plots/multi_cat/training/color/per_base_results.csv"

  # evaluation scripts cluster
  m_cluster_cat_eval_json: "data/synthetic_plots/multi_cat/training/cluster/cat_eval_summary.json"
  m_cluster_cat_eval_crop_csv: "data/synthetic_plots/multi_cat/training/cluster/per_crop_results.csv"
  m_cluster_cat_eval_base_csv: "data/synthetic_plots/multi_cat/training/cluster/per_base_results.csv"

unet:
  chkpt_path_color: "outputs/chkpt/0810-25_1529-52/unet_sd_cluster_mse_model_epoch80.pth" # the name has cluster but it was trained on color separated images
  output_dir_color: "data/synthetic_plots/multi_cat/training/color/denoised"

  chkpt_path_cluster: "outputs/chkpt/1011-25_0934-19/unet_sd_cluster_mse_model_epoch80.pth" # cluster
  output_dir_cluster: "data/synthetic_plots/multi_cat/training/cluster/denoised"






