paths:
  # CSV-style input
  real_dist_file:  "data/real_world_dis_info.xlsx"
  test_input_dir: "data/raw_synthetic/testing_data/data_1k"

  # Single-category plots
  s_plots: "data/synthetic_plots/single_cat/testing/images"
  s_dist_file: "data/synthetic_plots/single_cat/testing/dist_annotations.json"
  s_axes_file: "data/synthetic_plots/single_cat/testing/axes_annotations.json"
  s_crops: "data/synthetic_plots/single_cat/testing/s_crops/images"

  # Multi-category
  m_plots_svgs: "data/synthetic_plots/multi_cat/testing/svg_dir"
  m_plots: "data/synthetic_plots/multi_cat/testing/images"
  m_dist_file: "data/synthetic_plots/multi_cat/testing/dist_annotations.json"
  m_axes_file: "data/synthetic_plots/multi_cat/testing/axes_annotations.json"
  m_crops: "data/synthetic_plots/multi_cat/testing/m_crops/images"

  # Mult-Category Ground truth plots
  m_gt_plots_svgs: "data/synthetic_plots/multi_cat/testing/gt/svg_dir"
  m_gt_plots: "data/synthetic_plots/multi_cat/testing/gt/images"
  m_gt_axes_file: "data/synthetic_plots/multi_cat/testing/gt/gt_axes_annotations.json"
  m_gt_crops: "data/synthetic_plots/multi_cat/testing/gt_crops/images"
  m_gt_line_color: "data/synthetic_plots/multi_cat/testing/gt/gt_line_color.json"

  # Multi-category separated
  m_color_sep_plots: "data/synthetic_plots/multi_cat/testing/color/images"
  m_cluster_sep_plots: "data/synthetic_plots/multi_cat/testing/cluster/images"
  m_color_denoised_plots: "data/synthetic_plots/multi_cat/testing/color_denoised"
  m_cluster_denoised_plots: "data/synthetic_plots/multi_cat/testing/cluster_denoised"

  # Real-world plots
  real_plots: "data/real_plots/images"
  real_crops: "data/real_plots/crops"
  real_axes_file: "data/real_plots/r_axes_annotations.json"
  real_color_mapping: "data/real_plots/color_mapping.json"
  real_color_sep_plots: "data/real_plots/color/images"
  real_cluster_sep_plots: "data/real_plots/cluster/images"
  real_color_denoised_plots: "data/real_plots/color/denoised"
  real_cluster_denoised_plots: "data/real_plots/cluster/denoised"

unet:
  chkpt_path: "outputs/chkpt/unet_sd/unet_sd_clusternew_mse_model_epoch50.pth"
  input_dir: "data/real_plots/cluster/images"
  output_dir: "data/real_plots/cluster/denoised"

#  input_dir: "data/real_plots/color/images"
#  output_dir: "data/real_plots/cluster/images"
#
#  input_dir: "data/synthetic_plots/multi_cat/testing/color/images"
#  output_dir: "data/synthetic_plots/multi_cat/testing/color_denoised"
#
#  input_dir: "data/synthetic_plots/multi_cat/testing/cluster/images"
#  output_dir: "data/synthetic_plots/multi_cat/testing/cluster_denoised"


