paths:
  # CSV-style input
  real_dist_file:  "data/real_world_dis_info.xlsx"
  input_dir: "data/raw_synthetic/training_data/data_5k"

  # Multi-category full plots
  m_plots_svgs: "data/synthetic_plots/multi_cat/training/svg_dir"
  m_plots: "data/synthetic_plots/multi_cat/training/images"
  m_axes_file: "data/synthetic_plots/multi_cat/training/axes_annotations.json"
  m_dist_file: "data/synthetic_plots/multi_cat/training/dist_annotations.json"

  # Multi-category crops
  m_crops: "data/synthetic_plots/multi_cat/training/crops/images"
  m_all_json: "data/synthetic_plots/multi_cat/training/crops/all_data.json"
  m_train_json: "data/synthetic_plots/multi_cat/training/crops/train.json"
  m_valid_json: "data/synthetic_plots/multi_cat/training/crops/valid.json"

  # Ground truth plots
  m_gt_plots_svgs: "data/synthetic_plots/multi_cat/training/gt/svg_dir"
  m_gt_plots: "data/synthetic_plots/multi_cat/training/gt/images"
  m_gt_axes_file: "data/synthetic_plots/multi_cat/training/gt/gt_axes_annotations.json"
  m_gt_crops: "data/synthetic_plots/multi_cat/training/gt_crops/images"
  m_gt_line_color: "data/synthetic_plots/multi_cat/training/gt/gt_line_color.json"

  # Category separation - color
  m_color_sep_plots: "data/synthetic_plots/multi_cat/training/color/images"
  m_color_all_json: "data/synthetic_plots/multi_cat/training/color/all_data.json"
  m_color_train_json: "data/synthetic_plots/multi_cat/training/color/train.json"
  m_color_valid_json: "data/synthetic_plots/multi_cat/training/color/valid.json"
  m_color_all_json_merged: "data/synthetic_plots/multi_cat/training/color/merged_all_data.json"
  m_color_train_json_merged: "data/synthetic_plots/multi_cat/training/color/merged_train.json"
  m_color_valid_json_merged: "data/synthetic_plots/multi_cat/training/color/merged_valid.json"
  m_color_train_json_merged_rescaled: "data/synthetic_plots/multi_cat/training/color/rescaled_merged_train.json"
  m_color_valid_json_merged_rescaled: "data/synthetic_plots/multi_cat/training/color/rescaled_merged_valid.json"
  m_color_line_color: "data/synthetic_plots/multi_cat/training/color/line_color.json"
  m_color_denoised_plots: "data/synthetic_plots/multi_cat/training/color_denoised"

  # Category separation - clustering
  m_cluster_sep_plots: "data/synthetic_plots/multi_cat/training/cluster/images"
  m_cluster_all_json: "data/synthetic_plots/multi_cat/training/cluster/all_data.json"
  m_cluster_line_color: "data/synthetic_plots/multi_cat/training/cluster/line_color.json"
  m_cluster_train_json: "data/synthetic_plots/multi_cat/training/cluster/train.json"
  m_cluster_valid_json: "data/synthetic_plots/multi_cat/training/cluster/valid.json"
  m_cluster_all_json_merged: "data/synthetic_plots/multi_cat/training/cluster/merged_all_data.json"
  m_cluster_train_json_merged: "data/synthetic_plots/multi_cat/training/cluster/merged_train.json"
  m_cluster_valid_json_merged: "data/synthetic_plots/multi_cat/training/cluster/merged_valid.json"
  m_cluster_train_json_merged_rescaled: "data/synthetic_plots/multi_cat/training/cluster/rescaled_merged_train.json"
  m_cluster_valid_json_merged_rescaled: "data/synthetic_plots/multi_cat/training/cluster/rescaled_merged_valid.json"
  m_cluster_denoised_plots: "data/synthetic_plots/multi_cat/training/cluster_denoised"

  # Single-category
  s_plots: "data/synthetic_plots/single_cat/training/images"
  s_axes_file: "data/synthetic_plots/single_cat/training/axes_annotations.json"
  s_dist_file: "data/synthetic_plots/single_cat/training/dist_annotations.json"
  s_crops: "data/synthetic_plots/single_cat/training/s_crops/images"
  s_all_json: "data/synthetic_plots/single_cat/training/s_crops/all_data.json"




