paths:
  # CSV-style input
  input_dir: "data/raw_synthetic/training_data/data_5k"

  # Multi-category full plots
  m_plots: "data/synthetic_plots/training/multi_cat/images"
  m_axes_file: "data/synthetic_plots/training/multi_cat/axes_annotations.json"
  m_dist_file: "data/synthetic_plots/training/multi_cat/dist_annotations.json"

  # Multi-category crops
  m_crops: "data/synthetic_plots/training/multi_cat/crops/images"
  m_all_json: "data/synthetic_plots/training/multi_cat/crops/all_data.json"
  m_train_json: "data/synthetic_plots/training/multi_cat/crops/train.json"
  m_valid_json: "data/synthetic_plots/training/multi_cat/crops/valid.json"

  # Ground truth plots
  m_gt_plots: "data/synthetic_plots/training/multi_cat/gt/images"
  m_gt_axes_file: "data/synthetic_plots/training/multi_cat/gt/gt_axes_annotations.json"
  m_gt_crops: "data/synthetic_plots/training/multi_cat/gt_crops/images"
  m_gt_line_color: "data/synthetic_plots/training/multi_cat/gt/gt_line_color.json"

  # Category separation - color
  m_color_sep_plots: "data/synthetic_plots/training/multi_cat/color/images"
  m_color_all_json: "data/synthetic_plots/training/multi_cat/color/all_data.json"
  m_color_train_json: "data/synthetic_plots/training/multi_cat/color/train.json"
  m_color_valid_json: "data/synthetic_plots/training/multi_cat/color/valid.json"
  m_color_all_json_merged: "data/synthetic_plots/training/multi_cat/color/merged_all_data.json"
  m_color_train_json_merged: "data/synthetic_plots/training/multi_cat/color/merged_train.json"
  m_color_valid_json_merged: "data/synthetic_plots/training/multi_cat/color/merged_valid.json"
  m_color_train_json_merged_rescaled: "data/synthetic_plots/training/multi_cat/color/rescaled_merged_train.json"
  m_color_valid_json_merged_rescaled: "data/synthetic_plots/training/multi_cat/color/rescaled_merged_valid.json"
  m_color_line_color: "data/synthetic_plots/training/multi_cat/color/line_color.json"
  m_color_denoised_plots: "data/synthetic_plots/training/multi_cat/color_denoised"

  # Category separation - clustering
  m_cluster_sep_plots: "data/synthetic_plots/training/multi_cat/cluster/images"
  m_cluster_all_json: "data/synthetic_plots/training/multi_cat/cluster/all_data.json"
  m_cluster_line_color: "data/synthetic_plots/training/multi_cat/cluster/line_color.json"
  m_cluster_train_json: "data/synthetic_plots/training/multi_cat/cluster/train.json"
  m_cluster_valid_json: "data/synthetic_plots/training/multi_cat/cluster/valid.json"
  m_cluster_all_json_merged: "data/synthetic_plots/training/multi_cat/cluster/merged_all_data.json"
  m_cluster_train_json_merged: "data/synthetic_plots/training/multi_cat/cluster/merged_train.json"
  m_cluster_valid_json_merged: "data/synthetic_plots/training/multi_cat/cluster/merged_valid.json"
  m_cluster_train_json_merged_rescaled: "data/synthetic_plots/training/multi_cat/cluster/rescaled_merged_train.json"
  m_cluster_valid_json_merged_rescaled: "data/synthetic_plots/training/multi_cat/cluster/rescaled_merged_valid.json"
  m_cluster_denoised_plots: "data/synthetic_plots/training/multi_cat/cluster_denoised"

  # Single-category
  s_plots: "data/synthetic_plots/training/single_cat/images"
  s_axes_file: "data/synthetic_plots/training/single_cat/axes_annotations.json"
  s_dist_file: "data/synthetic_plots/training/single_cat/dist_annotations.json"
  s_crops: "data/synthetic_plots/training/single_cat/s_crops/images"
  s_all_json: "data/synthetic_plots/training/single_cat/s_crops/all_data.json"




